name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./cmd/gotouch/

    - name: test-make
      run: make unit-test

    - name: Unit Test
      run: go test -v  --tags=unit ./...
      
    - name: Integraton Test
      run: go test -v  --tags=integration ./...
