name: Build and Test

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
            composer install
            npm install
            npm run production

      - name: print version
        run: docker --version

      - name: Build
        run: make

      - name: Unit Test
        run: make unit-test

      - name: Integraton Test
        run: make integration-test
